#!/usr/bin/env node
const { execSync } = require("child_process");
const packageJson = require("../package.json");

console.log("Comparing version number before pushing into main");

const current_version = packageJson.version;

const latest_tag_hash = execSync(
  "git rev-list --tags --max-count=1"
).toString();

const latest_tag = execSync(
  `git describe --tags ${latest_tag_hash}`
).toString();

const latest_tag_number = latest_tag.replace("v", "");

if (current_version > latest_tag_number) {
  process.exitCode = 0;
  process.stdout.write(
    `true`
  );
} else {
  process.stderr.write(
    `false`
  );
  process.exitCode = 0;
}
