on:
  push:
    branches:
      - main
  release:
    types:
      - created

jobs:
  build:
    strategy:
      matrix:
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm install
      - run: npm test
        if: runner.os != 'Linux'
      - name: Tag
        if: success()
        id: create_tag
        uses: jaywcjlove/create-tag-action@main
        with:
          package-path: ./package.json
      - name: Publish
        if: success() && startsWith(github.ref, 'refs/tags/')
        run: npm run deploy
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
