name: Publish
on:
  workflow_run:
    workflows: [Create Tag]
    types: [completed]

jobs:
  publish-vscode:
    name: Publish VS Code
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run publish:vscode
  publish-openvsx:
    name: Publish Open VSX
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      OPENVSX_PAT: ${{ secrets.OPENVSX_PAT }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run publish:openvsx
