name: Publish
on:
  workflow_run:
    workflows: [Create Tag]
    types: [completed]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    env:
      VSCE_PAT: ${{ secrets.VSCE_PAT }}
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run deploy
