name: Create Tag
on:
  push:
    branches:
      - main
jobs:
  create_tag:
    name: Tag Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: Klemensas/action-autotag@1.2.3
        with:
          GITHUB_TOKEN: "${{ secrets.MY_GITHUB_TOKEN }}"
          tag_prefix: "v"
