name: Check Version
on:
  pull_request_target:
    branches: [main]

jobs:
  check_version:
    name: Check Version
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: npm install
      - run: npm run check:version
